# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- candidate/*

pool:
  vmImage: ubuntu-latest

variables:
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    noCache: true
    projects: 
      'Ready.Assessment.Backend/*.csproj' 
  displayName: 'Restore packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(System.DefaultWorkingDirectory)/Ready.Assessment.Backend.sln'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build'
